// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHall.Infrastructure.Persistense;

#nullable disable

namespace SmartHall.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHallDbContext))]
    [Migration("20240917151054_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Entities.HallEquipment.HallEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("HallEquipment", (string)null);
                });

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Entities.Reservation.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Period");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Halls", (string)null);
                });

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Entities.HallEquipment.HallEquipment", b =>
                {
                    b.HasOne("SmartHall.Domain.HallAggregate.Hall", null)
                        .WithMany("AvailableEquipment")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Entities.Reservation.Reservation", b =>
                {
                    b.HasOne("SmartHall.Domain.HallAggregate.Hall", null)
                        .WithMany("Reservations")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHall.Domain.HallAggregate.Hall", b =>
                {
                    b.Navigation("AvailableEquipment");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
